name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
    build:
        # ...
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2.0.1
              with:
                url: http://127.0.0.1:8200
                token: ${{ secrets.VaultToken }}
                #caCertificate: ${{ secrets.VAULTCA }}
                secrets: |
                    secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
                    secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;
                    secret/data/ci npm_token
            # ...
